const products = [
  {
    id: 1,
    name: 'Смартфон Xiaomi Redmi Note 12',
    description: '6.67-дюймовый AMOLED дисплей, 128 ГБ памяти, 8 ГБ ОЗУ',
    stock: 25,
    price: 19999,
    discount: 10,
  },
  {
    id: 2,
    name: 'Наушники Sony WH-CH720N',
    description: 'Беспроводные наушники с шумоподавлением, 35 часов работы',
    stock: 0,
    price: 12990,
    discount: 15,
  },
  {
    id: 3,
    name: 'Ноутбук Acer Nitro 5',
    description: '15.6 дюймов, Intel Core i5, NVIDIA GeForce RTX 3050',
    stock: 7,
    price: 74990,
    discount: 5,
  },
  {
    id: 4,
    name: "Кофемашина De'Longhi Magnifica S",
    description: 'Автоматическая кофемашина с капучинатором',
    stock: 12,
    price: 45990,
    discount: 20,
  },
  {
    id: 5,
    name: 'Фитнес-браслет Huawei Band 8',
    description: 'Трекер активности, мониторинг сна, 14 дней работы',
    stock: 34,
    price: 3990,
    discount: 0,
  },
  {
    id: 6,
    name: 'Электронная книга PocketBook 740',
    description: '7.8-дюймовый экран E Ink Carta, поддержка аудио',
    stock: 9,
    price: 27990,
    discount: 12,
  },
  {
    id: 7,
    name: 'Игровая консоль PlayStation 5',
    description: 'SSD 825 ГБ, 4K UHD Blu-ray, беспроводной геймпад',
    stock: 4,
    price: 69990,
    discount: 0,
  },
  {
    id: 8,
    name: 'Умная колонка Яндекс Станция 2',
    description: 'Голосовой помощник Алиса, поддержка музыки и умного дома',
    stock: 22,
    price: 14990,
    discount: 8,
  },
  {
    id: 9,
    name: 'Электрический чайник Bosch TWK 8611',
    description: '1.7 л, мощность 2400 Вт, скрытый нагревательный элемент',
    stock: 15,
    price: 3490,
    discount: 5,
  },
  {
    id: 10,
    name: 'Беспроводной пылесос Dyson V15 Detect',
    description: 'Мощный всас, лазерная подсветка пыли, до 60 минут работы',
    stock: 0,
    price: 59990,
    discount: 25,
  },
  {
    id: 11,
    name: 'Монитор Samsung Odyssey G5',
    description: '27 дюймов, 1440p, 144 Гц, изогнутый экран',
    stock: 11,
    price: 32990,
    discount: 10,
  },
  {
    id: 12,
    name: 'Блендер Philips HR3655',
    description: 'Мощность 1000 Вт, 5 скоростей, измельчитель и мельничка',
    stock: 20,
    price: 5990,
    discount: 15,
  },
  {
    id: 13,
    name: 'Внешний жесткий диск Seagate Expansion 2TB',
    description: 'USB 3.0, компактный корпус, совместимость с ПК и Mac',
    stock: 30,
    price: 5490,
    discount: 0,
  },
  {
    id: 14,
    name: 'Электросамокат Ninebot Max G30',
    description: 'Максимальная скорость 30 км/ч, запас хода 55 км',
    stock: 5,
    price: 49990,
    discount: 18,
  },
  {
    id: 15,
    name: 'Умные часы Apple Watch Series 9',
    description: '45 мм, GPS + Cellular, экран Always-On',
    stock: 0,
    price: 45990,
    discount: 7,
  },
];

const cart = [];

export { products, cart };
